### ISSUE TITLE
[Documentation] List avalaible options and their syntax

### ISSUE THREAD

**Issue by Mdyrl7777777** [smeso/saractl#3]
Hi! I hope I'm not annoying you with all those reports. SARA is interesting tool and I'm glad you create it. I'm currently trying to deploy it but I'm not sure about what options are avalaible and their correct syntax. I saw few example options in various places:

```
$ cat /etc/sara/wxprot.conf.d/99_wxprot.conf
#path flags
#* FULL,COMPLAIN,VERBOSE

$ cat /etc/sara/wxprot.conf.d/10_saratest.conf
/usr/bin/sara-test mprotect,verbose
/usr/lib/sara-test/* mprotect,verbose
/usr/lib/sara-test/procattr mmap,complain,verbose
/usr/lib/sara-test/fake_tramp mprotect,emutramp_or_mprotect,verbose
/usr/lib/sara-test/trampoline* mprotect,emutramp_or_mprotect,verbose
```

https://github.com/smeso/sara-test/blob/master/README.rst
```
SOURCE_PATH/bin/* mprotect,relro,verbose
SOURCE_PATH/bin/procattr relro,complain,verbose
SOURCE_PATH/bin/fake_tramp mprotect,emutramp,relro,verbose
SOURCE_PATH/bin/trampoline* mprotect,emutramp,relro,verbose
```

It would be nice to create list of all available and valid options and simple explanation how they can be used for blacklist or whitelist approach.

**EDIT:** ok, I found them here https://github.com/smeso/saractl/blob/ec5e9ab13be20d464d9f0286d9854b506fe686cd/sara/submodules/wxprot.py#L124 I'll study it.

**Comment by smeso** [comment]
I'm happy to receive comments and feedback! Please keep going!
The missing documentation is a known issue. Unfortunately there are other things to do with higher priority and 
I don't have too much free time. But I'll write it sooner or later :)

**Comment by smeso** [comment]
A lot of documentation is still missing, but ebb9ea03078e75332edad68a5e0b5dc1e5e376ff should solve this issue for now.
